print("Ingredientes")
input("     - 3 ovos")
input("     - 2 xícaras de açúcar")
input("     - 3 colheres de sopa de manteiga ou margarina")
input("     - 2 xícaras de farinha de trigo")
input("     - 1 xícara de leite")
input("     - 1 colher de sopa de fermento em pó")

print("Modo de preparo")
input("     - Em uma tigela, bata os ovos, o açúcar e a manteiga até formar um creme claro.")
input("     - Acrescente a farinha de trigo aos poucos, alternando com o leite.")
input("     - Misture bem até a massa ficar lisa.")
input("     - Adicione o fermento por último e mexa delicadamente.")
input("     - Despeje a massa em uma forma untada e enfarinhada.")
input("     - Leve ao forno preaquecido a 180 °C por cerca de 35 a 40 minutos.")
input("     - Espete um palito no centro do bolo; se sair limpo, está pronto.")